"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

    Triangle        Tn = n(n+1)/2          1, 3, 6, 10, 15, ...
    Pentagonal      Pn = n(3n−1)/2         1, 5, 12, 22, 35, ...
    Hexagonal       Hn = n(2n−1)           1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from math import sqrt

def is_triangle(number: int):
    """Check if n is a triangle number."""
    inverse = (sqrt(1 + 8 * number) - 1) / 2
    return inverse == int(inverse)

def is_pentagonal(number: int):
    """Check if number is a pentagonal number."""
    inverse = (sqrt(1 + 24 * number) + 1) / 6
    return inverse == int(inverse)

i = 143
while True:
    i += 1
    hexagonal = i * (2 * i - 1)
    if is_pentagonal(hexagonal):
        if is_triangle(hexagonal):
            print(hexagonal)
            break